# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-05 07:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20180205_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='key',
        ),
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
        migrations.AddField(
            model_name='file',
            name='Paper',
            field=models.CharField(default='0000000', max_length=100),
        ),
        migrations.AddField(
            model_name='file',
            name='School',
            field=models.CharField(default='0000000', max_length=100),
        ),
        migrations.AddField(
            model_name='file',
            name='SubCode',
            field=models.CharField(default='0000000', max_length=100),
        ),
        migrations.AddField(
            model_name='file',
            name='SubName',
            field=models.CharField(default='0000000', max_length=100),
        ),
        migrations.AddField(
            model_name='file',
            name='Year',
            field=models.CharField(default='0000000', max_length=100),
        ),
        migrations.AddField(
            model_name='file',
            name='uploaded_file_url',
            field=models.TextField(default='0000000'),
        ),
        migrations.AlterField(
            model_name='file',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 5, 7, 30, 55, 548111, tzinfo=utc), verbose_name='date published'),
        ),
    ]
