# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-05 07:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20180205_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 5, 7, 46, 18, 571278, tzinfo=utc), verbose_name='date published'),
        ),
    ]
