# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-05 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20180205_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
