# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-08 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_auto_20180205_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='Author',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
